# Generated by Django 4.1.7 on 2023-05-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_code",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
